### ISSUE TITLE
由earth主题切换joe3.0服务器500

### ISSUE THREAD

**Issue by xiedeacc** [jiewenhuang/halo-theme-joe3.0#181]
### 是什么版本出现了此问题？

2.12.0-SNAPSHOT

### 在线站点地址

https://blog.xiedeacc.com

### 发生了什么？

堆栈

```
2023-12-24T11:53:50.227+08:00  INFO 94739 --- [   scheduling-1] r.h.a.s.a.login.impl.RsaKeyService       : Generated RSA keys. Usage: 8121 ms.
2023-12-24T11:54:01.179+08:00 ERROR 94739 --- [oundedElastic-2] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-2] Exception processing template "index": An error happened during template rendering

org.thymeleaf.exceptions.TemplateOutputException: An error happened during template rendering
        at org.thymeleaf.engine.OutputTemplateHandler.handleText(OutputTemplateHandler.java:75) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleText(ProcessorTemplateHandler.java:587) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Text.beHandled(Text.java:97) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:1204) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:1204) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]

Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "(#strings.trim(theme.config.basic.source_link) !='' && theme.config.basic.enable_source_link)? theme.config.basic.source_link : '/themes/theme-Joe3'" (template: "modules/themeSettingVariable" - line 82, col 28)
        at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:29) ~[!/:2.12.0-SNAPSHOT]

Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from null to boolean
        at org.springframework.expression.spel.ast.OpAnd.assertValueNotNull(OpAnd.java:69) ~[spring-expression-6.1.1.jar!/:6.1.1]
        at org.springframework.expression.spel.ast.OpAnd.getBooleanValue(OpAnd.java:58) ~[spring-expression-6.1.1.jar!/:6.1.1]
        at org.springframework.expression.spel.ast.OpAnd.getValueInternal(OpAnd.java:52) ~[spring-expression-6.1.1.jar!/:6.1.1]




### 相关日志输出

_No response_

### 附加信息

_No response_

**Comment by jiewenhuang** [comment]
把所有设置保存一遍

**Comment by xiedeacc** [comment]
> 把所有设置保存一遍
管理页面的 System-> setting吗？ 全部保存了还是不行

**Comment by xiedeacc** [comment]
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/8072296/43051e61-0268-48c3-8c6d-ac7da4bae91c)
主题页面是这样的

**Comment by jiewenhuang** [comment]
卸载重装主题看看，这个主题设置都没出来
