### ISSUE TITLE
编译报缺少 webpack.config.js

### ISSUE THREAD

**Issue by qiushaocloud** [jiewenhuang/halo-theme-joe3.0#263]
### 是什么版本出现了此问题？

1.2.2

### 发生了什么？

编译报缺少 webpack.config.js，我修改后想编译下，生成相应的 .min 文件

### 相关日志输出

```shell
Debugger attached.

> halo-theme-joe3.0@1.1.6 build /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0
> webpack --config webpack.config.js

Debugger attached.
[webpack-cli] Failed to load '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/webpack.config.js' config
[webpack-cli] Error: Cannot find module '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/webpack.config.js'
Require stack:
- /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/bootstrap.js
- /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/bin/cli.js
- /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at WebpackCLI.tryRequireThenImport (/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js:223:30)
    at loadConfigByPath (/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
    at /Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js:1460:88
    at Array.map (<anonymous>)
    at WebpackCLI.loadConfig (/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js:1460:68)
    at WebpackCLI.createCompiler (/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js:1781:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack-cli/bin/cli.js',
    '/Users/qiushaocloud/Desktop/Codes/qiushao-git-codes/halo-theme-joe3.0/node_modules/webpack/bin/webpack.js'
  ]
}
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! halo-theme-joe3.0@1.1.6 build: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the halo-theme-joe3.0@1.1.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiushaocloud/.npm/_logs/2024-04-28T15_23_44_571Z-debug.log
Waiting for the debugger to disconnect...
```

**Comment by jiewenhuang** [comment]
现在这个项目并不是用webpack或者vite打包的项目，历史遗留问题，转化只能通过其他方式可以参考joe2文档
